import type {Assessment,Scenario,Range} from "./model";
export const known=(r:Range)=>r.low!==null&&r.high!==null&&Number.isFinite(r.low)&&Number.isFinite(r.high)&&r.low>=0&&r.low<=r.high;
export function exposure(s:Scenario){const included=s.financial.filter(f=>!f.excluded);const missing=s.financial.filter(f=>f.excluded?!f.source.trim():!known(f.range)||!f.source.trim());const partial={low:included.reduce((v,f)=>v+(f.range.low??0),0),high:included.reduce((v,f)=>v+(f.range.high??0),0)};const loss=missing.length?null:partial;const expected=loss&&known(s.probability)&&s.probability.high!<=100?{low:loss.low*s.probability.low!/100,high:loss.high*s.probability.high!/100}:null;const levels=['Unknown','Low','Medium','High'];const confidence=[s.confidence,...included.map(f=>f.confidence)].sort((a,b)=>levels.indexOf(a)-levels.indexOf(b))[0]||'Unknown';return {loss,partial,expected,missing,confidence};}
export const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Math.round(n/100)*100);
export const moneyRange=(r:Range|null)=>r&&known(r)?`${money(Math.floor(r.low!/100)*100)} – ${money(Math.ceil(r.high!/100)*100)}`:'UNKNOWN';
export function likelihood(s:Scenario,a:Assessment){if(!known(s.probability))return 'Unknown';const level=(n:number)=>n<a.thresholds.low?'Low':n<a.thresholds.high?'Medium':'High';const low=level(s.probability.low!),high=level(s.probability.high!);return low===high?low:`${low}–${high}`;}
export function priority(s:Scenario){const max=Math.max(...Object.values(s.severity));if(s.status==='Closed')return 'Closed';if(max>=4)return 'High';if(!known(s.probability)||!exposure(s).loss)return 'Investigate';return max===3?'Medium':'Low';}
export function graphAnalysis(a:Assessment){const upstream=(id:string)=>{const seen=new Set<string>();const walk=(x:string)=>{a.edges.filter(e=>e.target===x).forEach(e=>{if(e.source!==id&&!seen.has(e.source)){seen.add(e.source);walk(e.source);}})};walk(id);return [...seen];};return a.nodes.map(n=>({...n,inbound:a.edges.filter(e=>e.target===n.id).length,upstream:upstream(n.id),spof:a.edges.some(e=>e.target===n.id&&e.critical&&!e.alternative.trim())}));}
export function gaps(a:Assessment){const result:string[]=[];for(const [k,v]of Object.entries(a.company))if(v===null||v==='')result.push(`Company: ${k} is UNKNOWN`);a.systems.forEach(s=>{for(const k of ['vendor','controls','alternatives','recovery','source']as const)if(s[k]===null||s[k]==='')result.push(`${s.name}: ${k} is UNKNOWN`)});a.scenarios.forEach(s=>{const name=a.systems.find(t=>t.id===s.system)?.name;const e=exposure(s);if(!known(s.probability))result.push(`${name}: annual likelihood needs evidence`);if(e.missing.length)result.push(`${name}: ${e.missing.length} financial inputs or sources missing`);if(!s.approved)result.push(`${name}: scenario awaits analyst approval`);});return result;}
