import {baselineSchema,emptyBaseline,snapshotSchema,draftSchema,emptyDraft} from './simulation';
import { z } from "zod";
export const categories=["AI/ML","SaaS","Cloud infrastructure","Cybersecurity","Payments","ERP","CRM","Databases","Communications","Internal software","Third-party APIs","Vendors","Physical technology","Other"];
export const failureCategories=["Outage","Cyberattack","Data breach","AI model failure","Hallucination/error","Automation failure","Vendor failure","API failure","Cloud outage","Data corruption","Unauthorized access","Human error","Regulatory interruption","Supply interruption","Third-party service failure"];
export const costs=["Lost revenue","Downtime","Recovery costs","Incident-response costs","Vendor replacement","Customer remediation","Contractual penalties","Regulatory costs","Productivity losses"];
const txt=z.string().max(8000);const id=z.string().min(1).max(100);const num=z.number().finite().min(0).max(1e12).nullable();
export const rangeSchema=z.object({low:num,high:num}).refine(v=>v.low===null||v.high===null||v.low<=v.high,"Lower bound must not exceed upper bound");
export const origins=["Customer-provided fact","Analyst assumption","AI-generated hypothesis","Template hypothesis","Illustrative demo","Calculated value"] as const;
const origin=z.enum(origins);const confidence=z.enum(["Low","Medium","High","Unknown"]);
const systemSchema=z.object({id,name:z.string().trim().min(1).max(200),type:txt,vendor:txt,purpose:txt,boundary:txt,hosting:txt,ai:z.boolean(),users:num,processes:txt,sensitivity:txt,alternatives:txt,recovery:num,incidents:txt,controls:txt,critical:z.boolean(),source:txt,origin});
const nodeSchema=z.object({id,label:z.string().trim().min(1).max(200),kind:txt});const edgeSchema=z.object({id,source:id,target:id,critical:z.boolean(),alternative:txt});
const scenarioSchema=z.object({id,system:id,category:txt,description:txt,trigger:txt,immediate:txt,downstream:txt,processes:txt,downtime:rangeSchema,controls:txt,evidence:txt,notes:txt,origin,probability:rangeSchema,confidence,severity:z.object({operational:z.number().int().min(1).max(5),financial:z.number().int().min(1).max(5),customer:z.number().int().min(1).max(5),regulatory:z.number().int().min(1).max(5),reputation:z.number().int().min(1).max(5)}),controlStrength:z.enum(["Unknown","Weak","Moderate","Strong"]),status:z.enum(["Draft","Reviewed","Mitigating","Closed"]),approved:z.boolean(),financial:z.array(z.object({category:txt,range:rangeSchema,source:txt,origin,confidence,excluded:z.boolean()})).length(9),mitigation:z.object({action:txt,reduction:txt,difficulty:z.enum(["Low","Medium","High"]),rationale:txt,confidence})}).refine(v=>[v.probability.low,v.probability.high].every(n=>n===null||n<=100),"Probability must be 0–100%");
export const assessmentSchema=z.object({id,revision:z.number().int().nonnegative(),demo:z.boolean(),company:z.object({name:z.string().trim().min(1).max(200),industry:txt,revenue:num,employees:num,locations:num,activities:txt,products:txt,downtimeCost:num,regulations:txt,source:txt}),systems:z.array(systemSchema).max(100),nodes:z.array(nodeSchema).max(200),edges:z.array(edgeSchema).max(200),scenarios:z.array(scenarioSchema).max(200),thresholds:z.object({low:z.number().min(0).max(100),high:z.number().min(0).max(100)}),summary:txt,baseline:baselineSchema.default(emptyBaseline),simulationDraft:draftSchema.default(emptyDraft),simulations:z.array(snapshotSchema).max(30).default([])}).superRefine((a,c)=>{
const fail=(message:string)=>c.addIssue({code:"custom",message});
for(const rows of [a.systems,a.nodes,a.edges,a.scenarios,a.simulations])if(new Set(rows.map(x=>x.id)).size!==rows.length)fail("Duplicate IDs");
if(new Set(a.edges.map(e=>`${e.source}:${e.target}`)).size!==a.edges.length)fail("Duplicate dependency connections");
const ns=new Set(a.nodes.map(n=>n.id));const ss=new Set(a.systems.map(s=>s.id));
if(a.edges.some(e=>!ns.has(e.source)||!ns.has(e.target)||e.source===e.target))fail("Invalid dependency edge");
if(a.systems.some(s=>!ns.has(s.id)))fail("System missing from dependency graph");
if(a.scenarios.some(s=>!ss.has(s.system)))fail("Scenario references a missing system");
if(a.thresholds.low>=a.thresholds.high)fail("Likelihood thresholds must increase");
for(const s of a.scenarios){if(new Set(s.financial.map(f=>f.category)).size!==9||s.financial.some(f=>!costs.includes(f.category)))fail("Invalid financial categories");if(s.approved&&(!s.notes.trim()||s.status==='Draft'))fail("Approved risks need analyst notes and reviewed status");if(s.approved&&s.financial.some(f=>f.excluded&&!f.source.trim()))fail("Approved risks require an exclusion rationale for every excluded cost");}
});
export type Assessment=z.infer<typeof assessmentSchema>;export type System=Assessment['systems'][number];export type Scenario=Assessment['scenarios'][number];export type Range=z.infer<typeof rangeSchema>;
export const uid=()=>crypto.randomUUID();
export function blank():Assessment{return {id:uid(),revision:0,demo:false,company:{name:"Untitled assessment",industry:"",revenue:null,employees:null,locations:null,activities:"",products:"",downtimeCost:null,regulations:"",source:""},systems:[],nodes:[],edges:[],scenarios:[],thresholds:{low:10,high:40},summary:"",baseline:emptyBaseline(),simulationDraft:emptyDraft(),simulations:[]};}
export function newSystem():System{return {id:uid(),name:"New system",type:"SaaS",vendor:"",purpose:"",boundary:"External",hosting:"Cloud",ai:false,users:null,processes:"",sensitivity:"Unknown",alternatives:"",recovery:null,incidents:"",controls:"",critical:true,source:"",origin:"Customer-provided fact"};}
export function hypothesis(s:System,category="Outage"):Scenario{return {id:uid(),system:s.id,category,description:`${s.name} may become unavailable or produce unreliable outputs.`,trigger:"UNKNOWN — investigate initiating conditions",immediate:`Potential interruption to ${s.purpose||s.name}.`,downstream:"UNKNOWN — verify against dependency map",processes:s.processes,downtime:{low:null,high:null},controls:s.controls,evidence:"Rule-based scenario template; not evidence of an actual incident.",notes:"",origin:"Template hypothesis",probability:{low:null,high:null},confidence:"Unknown",severity:{operational:3,financial:3,customer:3,regulatory:3,reputation:3},controlStrength:"Unknown",status:"Draft",approved:false,financial:costs.map(category=>({category,range:{low:null,high:null},source:"",origin:"Analyst assumption",confidence:"Unknown",excluded:false})),mitigation:{action:s.ai?"Introduce human review and validate outputs before critical decisions.":"Test recovery procedures and evaluate an independent backup provider.",reduction:"UNKNOWN — validate control effectiveness before estimating reduction",difficulty:"Medium",rationale:"Template suggestion; confirm applicability and existing controls.",confidence:"Low"}};}
export function demo():Assessment{const a=blank();a.demo=true;a.company={name:"Northstar Commerce",industry:"Retail & e-commerce",revenue:24000000,employees:84,locations:3,activities:"Online ordering, fulfillment and customer support",products:"Consumer goods and subscription deliveries",downtimeCost:2500,regulations:"Payment card requirements; applicable privacy obligations — verify scope",source:"Illustrative sample data only; not a real company"};
const defs=[["Commerce platform","SaaS","Commerce vendor","Order capture"],["Payment gateway","Payments","Payments vendor","Payment acceptance"],["Cloud infrastructure","Cloud infrastructure","Cloud vendor","Application hosting"],["Support copilot","AI/ML","AI vendor","Customer support"]];a.systems=defs.map(([name,type,vendor,purpose])=>({...newSystem(),name,type,vendor,purpose,processes:purpose,ai:type==="AI/ML",recovery:8,controls:"Monitoring; daily backup (illustrative)",origin:"Illustrative demo" as const,source:"Illustrative sample"}));a.nodes=[{id:uid(),label:"Customer orders",kind:"Business process"},...a.systems.map(s=>({id:s.id,label:s.name,kind:s.ai?"AI system":"Technology system"}))];a.edges=[{id:uid(),source:a.nodes[0].id,target:a.systems[0].id,critical:true,alternative:""},{id:uid(),source:a.systems[0].id,target:a.systems[1].id,critical:true,alternative:""},{id:uid(),source:a.systems[0].id,target:a.systems[2].id,critical:true,alternative:""},{id:uid(),source:a.systems[3].id,target:a.systems[2].id,critical:true,alternative:""}];a.scenarios=a.systems.map((s,i)=>{const r=hypothesis(s,s.ai?"Hallucination/error":"Outage");r.origin="Illustrative demo";r.probability={low:10,high:25};r.downtime={low:4,high:24};r.confidence="Low";r.severity.operational=i===2?5:4;r.financial=r.financial.map(f=>({...f,range:f.category==="Downtime"?{low:10000,high:60000}:f.category==="Recovery costs"?{low:5000,high:15000}:{low:0,high:0},source:"Illustrative assumption; other components excluded to avoid overlap",origin:"Illustrative demo",confidence:"Low",excluded:!["Downtime","Recovery costs"].includes(f.category)}));return r;});return a;}
